package com.everis.springbootjpa.model;
// Generated 17/09/2019 04:25:31 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Compraproducto generated by hbm2java
 */
@Entity
@Table(name = "compraproducto", catalog = "cintegracion")
public class Compraproducto implements java.io.Serializable {

	private Integer idcompraproducto;
	private int idcompra;
	private int idproducto;
	private int cantidad;
	private BigDecimal preciounitario;

	public Compraproducto() {
	}

	public Compraproducto(int idcompra, int idproducto, int cantidad, BigDecimal preciounitario) {
		this.idcompra = idcompra;
		this.idproducto = idproducto;
		this.cantidad = cantidad;
		this.preciounitario = preciounitario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompraproducto", unique = true, nullable = false)
	public Integer getIdcompraproducto() {
		return this.idcompraproducto;
	}

	public void setIdcompraproducto(Integer idcompraproducto) {
		this.idcompraproducto = idcompraproducto;
	}

	@Column(name = "idcompra", nullable = false)
	public int getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(int idcompra) {
		this.idcompra = idcompra;
	}

	@Column(name = "idproducto", nullable = false)
	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "preciounitario", nullable = false, precision = 7)
	public BigDecimal getPreciounitario() {
		return this.preciounitario;
	}

	public void setPreciounitario(BigDecimal preciounitario) {
		this.preciounitario = preciounitario;
	}

}
