package com.everis.equipouno.model;
// Generated 20/09/2019 10:39:44 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prueba3 generated by hbm2java
 */
@Entity
@Table(name = "prueba3", catalog = "dbprueba")
public class Prueba3 implements java.io.Serializable {

	private int id;
	private String auto;
	private Set<Prueba2> prueba2s = new HashSet<Prueba2>(0);

	public Prueba3() {
	}

	public Prueba3(int id) {
		this.id = id;
	}

	public Prueba3(int id, String auto, Set<Prueba2> prueba2s) {
		this.id = id;
		this.auto = auto;
		this.prueba2s = prueba2s;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "auto", length = 45)
	public String getAuto() {
		return this.auto;
	}

	public void setAuto(String auto) {
		this.auto = auto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prueba3")
	public Set<Prueba2> getPrueba2s() {
		return this.prueba2s;
	}

	public void setPrueba2s(Set<Prueba2> prueba2s) {
		this.prueba2s = prueba2s;
	}

}
